# copied from https://github.com/sksamuel/hoplite/blob/master/.github/workflows/master.yml
name: Kotlin CI with Gradle

on:
  push:
    paths-ignore:
      - 'doc/**'
      - '*.md'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: run tests
        run: ./gradlew check

      - name: bundle the build report
        if: failure()
        run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

      - name: upload the build report
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: error-report
          path: build-reports.zip

